cuke:
  script:
    - make rebuild_services rebuild_patron_client rebuild_catalinker docker_compose_up test
  only:
    - develop
  stage: test

build:
  script:
    - LSDEVMODE=ci make rebuild_services rebuild_patron_client rebuild_catalinker login push
  only:
    - tags
  stage: build
