---
version: '3'

volumes:
  services_build: {}

services:

  build_services:
    container_name: build_services
    build:
      context: "${LSEXTPATH:-..}/redef/services"
      dockerfile: Dockerfile.build
    volumes:
      - "services_build:/services"

  services:
    build:
      context: "${LSEXTPATH}/redef/services"
      dockerfile: Dockerfile
    depends_on:
      - build_services
      - fuseki
      - koha
    environment:
      KOHA_MYSQL_USER: "${KOHA_ADMINUSER:-admin}"
      KOHA_MYSQL_PASS: "${KOHA_ADMINPASS:-secret}"
      KOHA_MYSQL_DB: "koha_${KOHA_INSTANCE:-name}"
      KOHA_API_PASS_ENCRYPTED: "$$2a$$08$$7WnfE3Fyh5W0C28Xp2SWH.NfgqLEZzw9oZI4qZ3MHf.lQS8yvv6hC"

  build_patron_client:
    container_name: build_patron_client
    build:
      context: "${LSEXTPATH:-..}/redef/patron-client"
      dockerfile: Dockerfile-build
    volumes:
      - "${LSEXTPATH:-..}/redef/patron-client/public:/usr/src/app/public"

  patron_client:
    build:
      context: "${LSEXTPATH:-..}/redef/patron-client"
      dockerfile: Dockerfile
    depends_on:
      - build_patron_client
      - services

  catalinker:
    build:
      context: "${LSEXTPATH:-..}/redef/catalinker"
      dockerfile: Dockerfile

  elasticsearch:
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"

