---
version: '3'

volumes:
  services_build: {}

services:

  build_services:
    container_name: build_services
    build:
      context: "${LSEXTPATH:-..}/redef/services"
      dockerfile: Dockerfile.build
    volumes:
      - "services_build:/services"

  services:
    build:
      context: "${LSEXTPATH}/redef/services"
      dockerfile: Dockerfile
    depends_on:
      - build_services
      - fuseki
      - koha
    environment:
      KOHA_MYSQL_USER: "${KOHA_ADMINUSER:-admin}"
      KOHA_MYSQL_PASS: "${KOHA_ADMINPASS:-secret}"
      KOHA_MYSQL_DB: "koha_${KOHA_INSTANCE:-name}"
      KOHA_API_PASS_ENCRYPTED: "$$2a$$08$$7WnfE3Fyh5W0C28Xp2SWH.NfgqLEZzw9oZI4qZ3MHf.lQS8yvv6hC"

  build_patron_client:
    container_name: build_patron_client
    build:
      context: "${LSEXTPATH:-..}/redef/patron-client"
      dockerfile: Dockerfile-build
    volumes:
      - "${LSEXTPATH:-..}/redef/patron-client/public:/usr/src/app/public"

  patron_client:
    build:
      context: "${LSEXTPATH:-..}/redef/patron-client"
      dockerfile: Dockerfile
    depends_on:
      - build_patron_client
      - services

  catalinker:
    build:
      context: "${LSEXTPATH:-..}/redef/catalinker"
      dockerfile: Dockerfile

  elasticsearch:
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"

  koha_mysql:
    container_name: koha_mysql
    image: mysql:5.6.20
    networks:
      - backend
    cap_add:
      - MKNOD
    command:
      - mysqld
      - "--datadir=/var/lib/mysql"
      - "--user=mysql"
      - "--max_allowed_packet=64M"
      - "--wait_timeout=6000"
      - "--bind-address=0.0.0.0"
      - "--server-id=101"
      - "--log_bin=mysql-bin"
      - "--sync_binlog=1"
      - "--binlog-format=row"
      - "--max_binlog_size=100M"
      - "--log_bin_trust_function_creators=true"
      - "--slow-query-log=1"
      - "--slow-query-log-file=/var/lib/mysql/slow-query.log"
      - "--long-query-time=10"
    environment:
      MYSQL_DATABASE: "koha_${KOHA_INSTANCE:-name}"
      MYSQL_PASSWORD: "${KOHA_ADMINPASS:-secret}"
      MYSQL_ROOT_PASSWORD: "${KOHA_ADMINPASS:-secret}"
      MYSQL_USER: "${KOHA_ADMINUSER:-admin}"
    volumes:
      - "koha_mysql_data:/var/lib/mysql"
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "2"
